### ISSUE TITLE
Architecture documentation TO-DO

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/ecsy#90]
To keep track of the documentation needed to include on https://github.com/fernandojsg/ecsy/blob/dev/docs/manual/Architecture.md

* [ ] Overview
* [x] World
* [x] Entities
  * [x] intro 
  * [x] Adding components
  * [x] Accessing components and mutability
  * [x] Removing components
* [x] Components
  * [x] intro
  * [x] clear
  * [x] copy
  * [x] Component pooling
  * [x] reset
  * [x] Tag Components
  * [x] Single value components
  * [x] System State Components
* [x] createComponentClass
* [x] Data types
* [x] System
  * [x] intro
  * [x] registering a system
  * [x] execution order
* [x] Queries
  * [x] intro
  * [x] not operator
  * [x] reactive queries
    * [x] added and removed
    * [x] changed
* [x] Life cycle

**Comment by fernandojsg** [comment]
Done
